---
## common playbook/NCSUrepos

## select repos by distribution and major
- name: Distrubution specific repos
  ansible.builtin.include_tasks: "{{ ansible_distribution | lower }}-{{ansible_distribution_major_version | lower }}.yaml"
  tags:
    - molecule
    - always

