---
## OracleLinux 8


  - name: Create Oracle Linux repo file
    ansible.builtin.yum_repository:
      name: "{{ item.name }}"
      description: "{{ item.desc }}"
      file: oracle-linux-ol8
      baseurl: "{{ item.url }}"
      gpgcheck: yes
      gpgkey: "file:///etc/pki/rpm-gpg/RPM-GPG-KEY-oracle"
      enabled: "{{ item.enabled }}"
    loop_control:
      label: "{{ item.label }}"
    loop:
      - { label: "Create Oracle Linux BaseOS latest entry", name: "ol8_baseos_latest", desc: "Oracle Linux 8 BaseOS Latest ($basearch)", url: "https://yum$ociregion.$ocidomain/repo/OracleLinux/OL8/baseos/latest/$basearch/", enabled: "yes"}
      - { label: "Create Oracle Linux AppStream latest entry", name: "ol8_appstream", desc: "Oracle Linux 8 Application Stream ($basearch)", url: "https://yum$ociregion.$ocidomain/repo/OracleLinux/OL8/appstream/$basearch/", enabled: "yes"}
      - { label: "Create Oracle Linux CodeReady Builder latest entry", name: "ol8_codeready_builder", desc: "Oracle Linux 8 CodeReady Builder ($basearch) - Unsupported", url: "https://yum$ociregion.$ocidomain/repo/OracleLinux/OL8/codeready/builder/$basearch/",enabled: "yes"}
      - { label: "Create Oracle Linux Distro Builder entry", name: "ol8_distro_builder", desc: "Oracle Linux 8 Distro Builder ($basearch) - Unsupported", url: "https://yum$ociregion.$ocidomain/repo/OracleLinux/OL8/distro/builder/$basearch/",enabled: "no"}
      - { label: "Create Oracle Linux 8.0 GA Base OS entry", name: "ol8_u0_baseos_base", desc: "Oracle Linux 8 BaseOS GA ($basearch)", url: "https://yum$ociregion.$ocidomain/repo/OracleLinux/OL8/0/baseos/base/$basearch/",enabled: "no"}
      - { label: "Create Oracle Linux 8.1 Base entry", name: "ol8_u1_baseos_base", desc: "Oracle Linux 8.1 Base OS ($basearch)", url: "https://yum$ociregion.$ocidomain/repo/OracleLinux/OL8/1/baseos/base/$basearch/", enabled: "no"}
      - { label: "Create Oracle Linux 8.2 Base entry", name: "ol8_u2_baseos_base", desc: "Oracle Linux 8.2 Base OS ($basearch)", url: "https://yum$ociregion.$ocidomain/repo/OracleLinux/OL8/2/baseos/base/$basearch/", enabled: "no"}
      - { label: "Create Oracle Linux 8.3 Base entry", name: "ol8_u3_baseos_base", desc: "Oracle Linux 8.3 Base OS ($basearch)", url: "https://yum$ociregion.$ocidomain/repo/OracleLinux/OL8/3/baseos/base/$basearch/", enabled: "no"}
      - { label: "Create Oracle Linux 8.4 Base entry", name: "ol8_u4_baseos_base", desc: "Oracle Linux 8.4 Base OS ($basearch)", url: "https://yum$ociregion.$ocidomain/repo/OracleLinux/OL8/4/baseos/base/$basearch/", enabled: "no"}
      - { label: "Create Oracle Linux 8.5 Base entry", name: "ol8_u5_baseos_base", desc: "Oracle Linux 8.5 Base OS ($basearch)", url: "https://yum$ociregion.$ocidomain/repo/OracleLinux/OL8/5/baseos/base/$basearch/", enabled: "no"}
      - { label: "Create Oracle Linux 8.6 Base entry", name: "ol8_u6_baseos_base", desc: "Oracle Linux 8.6 Base OS ($basearch)", url: "https://yum$ociregion.$ocidomain/repo/OracleLinux/OL8/6/baseos/base/$basearch/", enabled: "no"}
      - { label: "Create Oracle Linux 8 Addons entry", name: "ol8_addons", desc: "Oracle Linux 8 Addons ($basearch)", url: "https://yum$ociregion.$ocidomain/repo/OracleLinux/OL8/addons/$basearch/", enabled: "no"}
      - { label: "Create Oracle Linux 8 Security Validations entry", name: "ol8_u4_security_validation", desc: "Oracle Linux $releasever Update 4 ($basearch) Security Validations",url: "https://yum$ociregion.$ocidomain/repo/OracleLinux/OL8/4/security/validation/$basearch/",enabled: "no"}
  - name: Create Oracle Linux Unbreakable Kernel Repo 
    ansible.builtin.yum_repository:
      name: "{{ item.name }}"
      description: "{{ item.desc }}"
      file: uek-ol8
      baseurl: "https://yum$ociregion.$ocidomain/repo/OracleLinux/OL8/UEKR6/$basearch/"
      gpgcheck: yes
      gpgkey: "file:///etc/pki/rpm-gpg/RPM-GPG-KEY-oracle"
      enabled: "{{ item.enabled }}"
    loop_control:
      label: "{{ item.label }}"
    loop:
      -  {label: "Creating Unbreakable Enterprise Kernel Release 6 entry", name: "ol8_UEKR6",desc: "Latest Unbreakable Enterprise Kernel Release 6 for Oracle Linux $releasever ($basearch)", enabled: "yes"}
      -  {label: "Creating Oracle Linux 6 RDMA entry", name: "ol8_UEKR6_RDMA",desc: "Oracle Linux 8 UEK6 RDMA ($basearch)", enabled: "no"}

  - name: Create Oracle Linux KVM Repo
    ansible.builtin.yum_repository:
      name: ol8_kvm_appstream
      description: "Oracle Linux $releasever KVM Application Stream ($basearch)"
      file: ol8.repo
      baseurl: "https://yum$ociregion.$ocidomain/repo/OracleLinux/OL8/kvm/appstream/$basearch/"
      gpgkey: "file:///etc/pki/rpm-gpg/RPM-GPG-KEY-oracle"
      gpgcheck: yes
      enabled: no
