FROM oraclelinux:7.9

LABEL maintainer="Shaun Sundquist <sjsundqu@ncsu.edu>"
LABEL build_date="2022-08-23"

ENV container=docker

RUN yum -y reinstall systemd
RUN yum -y install systemd-libs systemd-sysv systemd-219
RUN cd /etc/systemd/system/sysinit.target.wants/ ; \
    for i in * ; do [ $i = systemd-tmpfiles-setup.service ] || rm -f $i ; done ; \
    rm -f /lib/systemd/system/multi-user.target.wants/* ; \
    rm -f /etc/systemd/system/*.wants/* ; \
    rm -f /lib/systemd/system/local-fs.target.wants/* ; \
    rm -f /lib/systemd/system/sockets.target.wants/*udev* ; \
    rm -f /lib/systemd/system/sockets.target.wants/*initctl* ; \
    rm -f /lib/systemd/system/basic.target.wants/* ; \
    rm -f /lib/systemd/system/anaconda.target.wants/*

VOLUME ["/sys/fs/cgroup"]

CMD ["/usr/sbin/init"]
