---
dependency:
  name: galaxy
driver:
  name: docker

platforms:
  - name: oracle7
    pre_build_image: false
    dockerfile: Dockerfile.ol7
    image: oraclelinux:7.9
    docker_host: "${DOCKER_HOST:-unix://var/run/docker.sock}"
    privileged: true
    command: /usr/sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - molecule
      - python3

  - name: oracle8
    pre_build_image: false
    dockerfile: Dockerfile.ol8
    image: oraclelinux:8.5
    docker_host: "${DOCKER_HOST:-unix://var/run/docker.sock}"
    privileged: true
    command: ${MOLECULE_DOCKER_COMMAND:-"/usr/sbin/init"}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - molecule
      - python3

provisioner:
  name: ansible
  playbooks:
    prepare: prepare.yml
  inventory:
    host_vars:
      oracle7:
        ora_asg_subnet: 10.32.14.0/23
        ora_asg_ip: 152.1.7.12 # asgateway ip
        ora_asg_device: eth0 # device for ora_jump_ip
        ora_tblnum: 220
      # oracle8:
      #   ip: 2.2.2.2
    group_vars:
      molecule:
        run_is_molecule: true

verifier:
  name: ansible

lint: |
  set -e
  yamllint .
  ansible-lint
  # flake8
