---
dependency:
  name: galaxy
driver:
  name: docker

platforms:
  - name: oracle7
    pre_build_image: false
    dockerfile: Dockerfile.ol7
    image: oraclelinux:7.9
    docker_host: "${DOCKER_HOST:-unix://var/run/docker.sock}"
    privileged: true
    command: /usr/sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - molecule

  - name: oracle8
    pre_build_image: false
    dockerfile: Dockerfile.ol8
    image: oraclelinux:8.5
    docker_host: "${DOCKER_HOST:-unix://var/run/docker.sock}"
    privileged: true
    command: ${MOLECULE_DOCKER_COMMAND:-"/usr/sbin/init"}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - molecule

provisioner:
  name: ansible
  playbooks:
    prepare: prepare.yml
  inventory:
    group_vars:
      molecule:
        run_is_molecule: true

verifier:
  name: ansible

lint: |
  set -e
  yamllint .
  ansible-lint
  # flake8
