---
 containers:
   hosts:
     alma:
       ansible_user: ansible
       ansible_host: localhost
       ansible_hostname: node-01.localhost
       ansible_port: 2222

     ub22:
       ansible_user: ansible
       ansible_host: localhost
       ansible_hostname: node-02.localhost
       ansible_port: 2221
