---
# defaults file for autofs
ps_path: test
write_date: "{{ lookup('pipe', 'date +%Y-%m-%d@%H:%M') }}"

# defaults for autofs
timeout_sec: 300
browse_mode: "no"
dismount_interval: 300

# --- OS config ---
autofs_master:
  Linux: "/etc/auto.master"

__autofs_requirements:
  default: []
  RedHat:
    - nfs-utils
  Debian: 
    - procps
    - nfs-common
  OracleLinux: []
  CentOS:
    - nfs-utils

autofs_requirements: "{{ _autofs_requirements[ansible_os_family] | default(_autofs_requirements['default']) }}"

autofs_mounts: []

__autofs_maps: []