---
dependency:
  name: galaxy
driver:
  name: docker
platforms:

  - name: oracle7
    pre_build_image: false
    dockerfile: Dockerfile.ol7
    image: oraclelinux:7.9
    docker_host: "${DOCKER_HOST:-unix://var/run/docker.sock}"
    privileged: true
    command: /usr/sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - python3

  - name: oracle8
    pre_build_image: false
    dockerfile: Dockerfile.ol8
#   registry:
#     url: docker.io
#   capabilities:
#     - SYS_ADMIN
    image: oraclelinux:8.5
    docker_host: "${DOCKER_HOST:-unix://var/run/docker.sock}"
    privileged: true
    command: ${MOLECULE_DOCKER_COMMAND:-"/usr/sbin/init"}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - python3

provisioner:
  name: ansible
  playbooks:
    prepare: prepare.yml
    converge: playbook.yml
  inventory:
    group_vars:
      python3:
        ansible_python_interpreter: /usr/bin/python3

provisioner:
  name: ansible
verifier:
  name: ansible