---
- name: Prepare
  hosts: all
  tasks:
    - name: Install python3
      package:
        name: python3

    - name: Install sudo
      package:
        name: sudo
      changed_when: false

## begin oraclelinux version spefic preparation.
# Oracle8
    - name: Oracle8 specific items
      block:
        - name: Copy in SystemD systemctl replacement
          copy:
            src: "files/docker/systemctl3.py"
            dest: "/usr/bin/systemctl"
            backup: true
            force: true
            mode: '0755'
          become: true

        - name: Copy in SystemD journalctl replacement
          copy:
            src: "files/docker/journalctl3.py"
            dest: "/usr/bin/journalctl"
            backup: true
            force: true
            mode: '0755'

      when:
        - ansible_distribution == "OracleLinux"
        - ansible_distribution_major_version == "8"

# Oracle 7
    - name: Oracle7 specific items
      block:
        - name: OL7 - Copy in SystemD systemctl replacement
          copy:
            src: "files/docker/systemctl3.py"
            dest: "/usr/bin/systemctl"
            backup: true
            force: true
            mode: '0755'

        - name: OL7 - Copy in SystemD journalctl replacement
          copy:
            src: "files/docker/journalctl3.py"
            dest: "/usr/bin/journalctl"
            backup: true
            force: true
            mode: '0755'

        - name: OL7 - Create /run/dbus directory
          file:
            path: /run/dbus
            state: directory

        - name: OL7 - Start dbus-daemon
          ansible.builtin.command: dbus-daemon --system

      when:
        - ansible_distribution == "OracleLinux"
        - ansible_distribution_major_version == "7"

