---

- name: Creating hard mount(s) for autofs
  ansible.builtin.file:
    path: "{{ autofs_mount_point | default(omit) }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  loop_control:
    loop_var: autofs_mount_point
    label: "Creating hard mount: {{ autofs_mount_point }}."
  loop: "{{ autofs_mounts }}"
  tags:
    - always
    - molecule

- name: "[OracleLinux] Install autofs and enable disabled repo"
  ansible.builtin.package:
    name: autofs
    state: present
    enablerepo: ol7_latest
  when: ansible_distribution == "OracleLinux"
  tags:
    - always
    - molecule

- name: "[RHEL/CentOS/Ubuntu] Install autofs"
  ansible.builtin.package:
    name: autofs
    state: present
    update_cache: true
  when: ansible_distribution != "OracleLinux"
  tags:
    - always
    - molecule

- name: "Enable systemd autofs"
  ansible.builtin.systemd:
    name: autofs
    enabled: true
  tags:
    - always
    - no_molecule

## Copy our configs
- name: Copy defined configuration of autofs to hosts
  ansible.builtin.template:
    src: templates/autofs.j2
    dest: "{% if (item.master_dir is defined) and (item.master_dir) %}/etc/auto.master.d/auto.{{item.file}}{% else %}/etc/auto.{{item.file}}{% endif %}"
    owner: root
    group: root
    mode: 0644
    force: yes
  loop: "{{ autofs_maps| default(__autofs_maps) }}"
  tags:
    - always
    - no_molecule
  notify: restart autofs

