---

  - name: Create host directory in {{ playbook_dir }}/demo/container_files/ 
    ansible.builtin.file:
      path: "{{ playbook_dir }}/demo/container_files/{{ container.name }}"
      state: directory

  - name: Creating Image Containerfile for {{ container.build_image }}
    ansible.builtin.template:
      src: ../templates/build_template.j2
      dest: "{{ playbook_dir }}/demo/container_files/{{ container.name }}/Containerfile"

  - name: Pulling base image {{ container.base_image }}
    containers.podman.podman_image:
      name: "{{container.base_image}}"
      tag: "{{container.tag}}"
      pull: true 

  - name: Building Image {{ container.build_image }} from Containerfile
    containers.podman.podman_image:
      build: 
        file: "{{ playbook_dir }}/demo/container_files/{{ container.name }}/Containerfile"
      name: "{{ container.base_image }}"
      state: present
