---
dependency:
  name: galaxy
driver:
  name: podman

platforms:
  - name: defaultinstance
    image: ubi8/ubi-init:latest
    pre_build_image: true
    docker_host: "${DOCKER_HOST:-unix://var/run/docker.sock}"
    privileged: true
    command: ${MOLECULE_DOCKER_COMMAND:-"/usr/sbin/init"}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - molecule
      - python3

provisioner:
  name: ansible
  inventory:
    group_vars:
      molecule:
        run_is_molecule: true

verifier:
  name: ansible

lint: |
  set -e
  yamllint .
  ansible-lint
  # flake8