---
- name: Prepare
  hosts: all
  tasks:
    - name: Install python3
      package:
        name: python3

    - name: Install sudo
      package:
        name: sudo
      changed_when: false

    - name: Copy in SystemD systemctl replacement
      copy: src="files/docker/systemctl3.py" dest="/usr/bin/systemctl"

    - name: Copy in SystemD journalctl replacement
      copy: src="files/docker/journalctl3.py" dest="/usr/bin/journalctl"
