---
dependency:
  name: galaxy
  options:
    ignore-errors: True

driver:
  name: podman

platforms:

  - name: ubi8
    image: ubi8/ubi-init
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    command: "/usr/sbin/init"

provisioner:
  name: ansible
  playbooks:
    prepare: prepare.yml
  # inventory:
  #   group_vars:
  #     python3:
  #       ansible_python_interpreter: /usr/bin/python3

verifier:
  name: ansible
