---
# This is an example playbook to execute Ansible tests.
# This allows you to write specific tests against the state
# of the container after your role has finished executing.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: Example assertion
    assert:
      that: true
