---
dependency:
  name: galaxy

driver:
  name: podman

platforms:

  - name: oracle7
    pre_build_image: true
    image: docker.io/oraclelinux:7.9
    docker_host: "${DOCKER_HOST:-unix://var/run/docker.sock}"
    privileged: true
    command: "/usr/sbin/init"
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - python3

  - name: oracle8
    pre_build_image: true
    image: docker.io/oraclelinux:8
    docker_host: "${DOCKER_HOST:-unix://var/run/docker.sock}"
    privileged: true
    command: "/usr/sbin/init"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - python3

provisioner:
  name: ansible
  playbooks:
    prepare: prepare.yml

verifier:
  name: ansible