---
## nslcd playbook/handlers

- name: "restart nslcd"
  service:
    name: nslcd
    state: restarted
  when: "'molecule' not in ansible_run_tags"
  tags:
    - always
    - no_molecule

- name: "enable nslcd"
  service:
    name: nslcd
    enabled: true
  when: "'molecule' not in ansible_run_tags"
  tags:
    - always
    - no_molecule

- name: "restart nscd"
  service:
    name: nscd
    state: restarted
  when: "'molecule' not in ansible_run_tags"
  tags:
    - always
    - no_molecule