---
 - name: Script Demo
   hosts: demo-node-02
   gather_facts: true


   tasks:
     - ansible.builtin.apt_repository:
         repo: "deb https://packages.linux.ncsu.edu/priv/ubuntu/{{ ansible_distribution_release }}"
         state: present
         filename: tenable_nessus
       become: true 
     
   
