---
 - name: Running rol on all hosts
   hosts: all
   gather_facts: true
   tags: never

   #vars:
   #vars_files:
   #vars_prompt:
   #pre_tasks:
   roles:
     - role: hello
       notify: Print OS
   #tasks:
   #post_tasks:
   handlers:
     - name: Print OS
       ansible.builtin.debug:
         msg: "{{ ansible_distribution }}" 


 - name: Running against UB22 only
   hosts: ub22
   gather_facts: true
   tags: always

   tasks:

     - name: Show me the family
       ansible.builtin.debug:
         msg: 
           - "{{ ansible_os_family }}"
           - "{{ ansible_distribution }}"
           - "{{ ansible_distribution_major_version }}"
           - "{{ ansible_facts['os_family'] }}"
