---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: CentOS8Stream
    image: geerlingguy/docker-centos8-ansible:latest
    pre_build_image: true
    docker_host: "${DOCKER_HOST:-unix://var/run/docker.sock}"
    privileged: true
    command: ${MOLECULE_DOCKER_COMMAND:-"/usr/sbin/init"}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - python3
provisioner:
  name: ansible
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint
  # flake8