---
## nslcd playbook/tasks
- name: Copy certs
  ansible.builtin.include_tasks: certs.yml
  tags:
    - configuration
    - always
    - molecule

- name: OL7 Install packages
  block:
    - name: "OL7 - install nslcd and nss-pam-ldapd"
      ansible.builtin.package:
        name: '{{ item.pkg }}'
        state: '{{ item.stat }}'
        enablerepo: "ol7_latest"
      with_items:
        - { pkg: 'nscd', stat: 'present' }
        - { pkg: 'nss-pam-ldapd', stat: 'present' }
      become: true
  when:
    - ansible_distribution_major_version == "7"
    - ansible_distribution == "OracleLinux"
  tags:
    - always
    - molecule

- name: OL8 Install packages
  block:
    - name: "OL8 - install nslcd and nss-pam-ldapd"
      ansible.builtin.package:
        name: '{{ item.pkg }}'
        state: '{{ item.stat }}'
      with_items:
        - { pkg: 'nscd', stat: 'present' }
        - { pkg: 'nss-pam-ldapd', stat: 'present' }
      become: true
  when:
    - ansible_distribution_major_version == "8"
    - ansible_distribution == "OracleLinux"
  tags:
    - always
    - molecule

- name: Setup IPA nslcd configs
  ansible.builtin.include_tasks: nslcd-ipa.yml
  when: enable_ipa is true
  tags:
    - always
    - molecule

- name: Setup regular nslcd configs
  ansible.builtin.include_tasks: nslcd.yml
  when: not enable_ipa
  tags:
    - always
    - molecule
