---
# setup ncsu configs

- name: Copy nslcd configs to host...
  ansible.builtin.template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    owner: '{{ item.owner }}'
    group: '{{ item.grp }}'
    mode: '{{ item.mode }}'
    force: '{{ item.force }}'
    backup: true
  with_items:
    - { src: 'templates/nslcd.conf.j2', dest: '/etc/nslcd.conf', owner: 'root', grp: 'root', mode: '0600', force: 'yes' }
  tags:
    - always
    - molecule
    - configuration
  when: not enable_ipa
  become: true
  notify:
    - enable nslcd
    - restart nslcd
    - restart nscd
